/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserHauptmenue;

import GUI_Internalframes.*;

import Interfaces.*;
import javax.swing.JInternalFrame;
import JFrames.*;
import java.awt.Component;
import javax.swing.tree.TreePath;

/**
 *
 * @author Luca Terrasi
 *
 * 10.12.2014 Terrasi,Erstellung.
 * 02.01.2015 Terrasi, JTreenavigation erstellt und einbindung der Guifactory
 */
public class Hauptmenue_User extends javax.swing.JInternalFrame implements InterfaceJTreeFunction {
    /*
     Hilfsvariablen
     */

    TreePath node; // Speichervariable für den Pfand des Jtrees
    String pfad;// Speichervariable für den Wert des Blattes eines JTrees
    Start internal;// Referenzvariable des Internalframes

    GUIFactory factory;//Speichervariable für die zu übergebenen Factory

    /*----------------------------------------------------------*/
    /* Datum Name Was */
    /* 10.12.2014 Terrasi angelegt */
    /* 02.01.2015 Terrasi Überarbeitung des Konstruktors */
    /*----------------------------------------------------------*/
    /**
     * Creates new form test
     *
     */
    public Hauptmenue_User(GUIFactory factory, Component frame) {
        initComponents();
        this.factory = factory;//Übergabe der Factory.
        try {
            this.internal = (Start) frame;//Übergebene Component wird gecastet und
                                          // in Hilfsvariable gespeichert.
        } catch (Error e) {// Fehlerbehandlung, falls ein ein Component nicht  
                           // gecastet werden kann.
            System.out.println(e.getMessage());// Ausgabe des Fehlers
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hauptmenu_jScrollPane = new javax.swing.JScrollPane();
        hauptmenueAdmin_Tree = new javax.swing.JTree();
        Logo_jLabel = new javax.swing.JLabel();
        Statuszeile_jTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jB_Zurueck = new javax.swing.JButton();
        jB_Abbrechen = new javax.swing.JButton();
        jB_Speichern = new javax.swing.JButton();
        jB_Anzeigen = new javax.swing.JButton();
        jB_Loeschen = new javax.swing.JButton();
        jB_Suchen = new javax.swing.JButton();

        setResizable(true);
        setTitle("Hauptmenü");
        setVisible(true);

        hauptmenueAdmin_Tree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Navigation");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Auftrag verwalten");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Auftragskopf");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Anlegen");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Ändern");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Anzeigen");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Auftragsposition");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Ändern");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Anzeigen");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Artikel verwalten");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Anlegen");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ändern");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Anzeigen");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Geschäftspartner verwalten");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Anlegen");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ändern");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Anzeigen");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Zahlungskonditionen verwalten");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Anlegen");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ändern");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Anzeigen");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        hauptmenueAdmin_Tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        hauptmenueAdmin_Tree.setName("Navigation"); // NOI18N
        hauptmenueAdmin_Tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hauptmenueAdmin_TreeMouseClicked(evt);
            }
        });
        Hauptmenu_jScrollPane.setViewportView(hauptmenueAdmin_Tree);

        Logo_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminHauptmenue/logo.PNG"))); // NOI18N

        Statuszeile_jTextField.setBackground(new java.awt.Color(240, 240, 240));
        Statuszeile_jTextField.setText("Statuszeile");
        Statuszeile_jTextField.setEnabled(false);

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        jB_Zurueck.setText("Zurück");
        jB_Zurueck.setEnabled(false);
        jToolBar1.add(jB_Zurueck);

        jB_Abbrechen.setText("Abbrechen");
        jB_Abbrechen.setEnabled(false);
        jToolBar1.add(jB_Abbrechen);

        jB_Speichern.setText("Speichern");
        jB_Speichern.setEnabled(false);
        jToolBar1.add(jB_Speichern);

        jB_Anzeigen.setText("Anzeige/Ändern");
        jB_Anzeigen.setEnabled(false);
        jToolBar1.add(jB_Anzeigen);

        jB_Loeschen.setText("Löschen");
        jB_Loeschen.setEnabled(false);
        jToolBar1.add(jB_Loeschen);

        jB_Suchen.setText("Suchen");
        jToolBar1.add(jB_Suchen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hauptmenu_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logo_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
            .addComponent(Statuszeile_jTextField)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(Hauptmenu_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Statuszeile_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*----------------------------------------------------------*/
    /* Datum Name Was */
    /* 10.12.2014 Terrasi angelegt */
    /* 02.01.2015 Terrasi  Zuweisung der Schnittstellenmethode OpenJtreeNodes/
    /*----------------------------------------------------------*/
    private void hauptmenueAdmin_TreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hauptmenueAdmin_TreeMouseClicked
        try {
            node = hauptmenueAdmin_Tree.getSelectionPath();
            pfad = node.toString();
            if (evt.getClickCount() == 2) {
                openJtreeNodes(pfad);
            }
            System.out.println(pfad);

        } catch (NullPointerException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_hauptmenueAdmin_TreeMouseClicked

    /*----------------------------------------------------------*/
    /* Datum Name Was */
    /* 10.12.2014 Terrasi angelegt */
    /* 02.01.2015 Terrasi  Überarbeitung der Funktion*/
    /*----------------------------------------------------------*/
    @Override
    public void openJtreeNodes(String node) {
        try {

            if (node != null) {
                System.out.println("aaaaaaaaa");
                if (node.equals("[Navigation, Auftrag verwalten, Auftragskopf, Anlegen]")) {
                    this.internal.setFrame(this.internal.auftragskopfanlegen);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Auftrag verwalten, Auftragskopf, Ändern]")) {
                    this.internal.setFrame(this.internal.auftragskopfaendern);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Auftrag verwalten, Auftragskopf, Anzeigen]")){
                    
                }
                if (node.equals("[Navigation, Auftrag verwalten, Auftragsposition, Ändern]")){
                    this.internal.setFrame(this.internal.auftragsspositionaender);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Auftrag verwalten, Auftragsposition, Anzeigen]")){
                    this.internal.setFrame(this.internal.auftragsspositionanzeigen);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Artikel verwalten, Anlegen]")){
                    this.internal.setFrame(this.internal.artikelanlegen);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Artikel verwalten, Ändern]")){
                    this.internal.setFrame(this.internal.artikelaendern);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Artikel verwalten, Anzeigen]")){
                    
                }
                if (node.equals("[Navigation, Geschäftspartner verwalten, Anlegen]")){
                    this.internal.setFrame(this.internal.geschaeftspartneranlegen);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Geschäftspartner verwalten, Ändern]")){
                    this.internal.setFrame(this.internal.geschaeftspartneraendern);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Geschäftspartner verwalten, Anzeigen]")){
                    
                }
                if (node.equals("[Navigation, Zahlungskonditionen verwalten, Anlegen]")){
                    this.internal.setFrame(this.internal.zahlungskonditionanlegen);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Zahlungskonditionen verwalten, Ändern]")){
                    this.internal.setFrame(this.internal.zahlungskonditionaendern);
                    this.factory.setComponent(this.internal.hauptmenueuser);
                    this.setVisible(false);
                }
                if (node.equals("[Navigation, Zahlungskonditionen verwalten, Anzeigen]")){
                    
                }
                
            }
        } catch (NullPointerException e) {
            System.out.println(e.getMessage());
        }
    }

    @Override
    public void setInternalFrameVisible(JInternalFrame frame) {
//        if( frame.getName().equals("Auftragskopf"))
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Hauptmenu_jScrollPane;
    private javax.swing.JLabel Logo_jLabel;
    private javax.swing.JTextField Statuszeile_jTextField;
    private javax.swing.JTree hauptmenueAdmin_Tree;
    private javax.swing.JButton jB_Abbrechen;
    private javax.swing.JButton jB_Anzeigen;
    private javax.swing.JButton jB_Loeschen;
    private javax.swing.JButton jB_Speichern;
    private javax.swing.JButton jB_Suchen;
    private javax.swing.JButton jB_Zurueck;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
