package GUI_Internalframes;

import DAO.ApplicationException;
import DTO.Artikel;
import Documents.UniversalDocument;
import Interfaces.InterfaceMainView;
import JFrames.*;
import java.awt.Component;
import java.text.NumberFormat;
import java.text.ParseException;

/**
 * Klasse fuer die Maske Artikel aendern/anzeigen Einstieg je nachdem von
 * welchem Button diese Klasse aufgerufen wird aendert sie sich in den Zustand
 * Artikel aendern Einstieg oder Artikel anzeigen Einstieg
 *
 * @author Tahir
 */
public class ArtikelAEndernEinstieg extends javax.swing.JInternalFrame {

    /**
     * Variable, die für die Navigation benoetigt wird, in ihr wird gespeichert,
     * welche View zuletzt geöffnet war.
     */
    private Component c;
    /**
     * Varibale für die GUI Factory
     */
    private GUIFactory factory;
    /**
     * Variable für das Start Fenster. Es kann sein, dass sich ein Admin
     * anmeldet, dann waere unser StartFenster die StartAdmin. Falls sich ein
     * User anmeldet, ist unser StartFenster Start.
     */
    private InterfaceMainView hauptFenster;
    /**
     * Referenzvaribale der Sicht Artikel anlegen
     */
    private ArtikelAnlegen artikelAnlegen;
    /**
     * Number Formatter wird benoetigt fuer das Parsen der Eingaben, sowie das
     * Anzeigen von Preisen
     */
    private NumberFormat nf;

    /**
     * Konstruktor der Klasse, erstellt die benötigten Objekte und setzt die
     * Documents.
     *
     * @param factory beinhaltet das factory Obejekt
     * @param artikelAnlegen Referenzvariable der Artikel anlegen Klasse
     * @param mainView beinhaltet das Objekt des StartFenster
     */
    public ArtikelAEndernEinstieg(GUIFactory factory, ArtikelAnlegen artikelAnlegen, InterfaceMainView mainView) {
        initComponents();
        this.factory = factory;
        this.artikelAnlegen = artikelAnlegen;
        this.hauptFenster = mainView;
        nf = NumberFormat.getInstance();
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);
        jTF_Artikel_ID.setDocument(new UniversalDocument("0123456789", false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jB_Zurueck = new javax.swing.JButton();
        jB_Speichern = new javax.swing.JButton();
        jB_Anzeigen = new javax.swing.JButton();
        jB_Loeschen = new javax.swing.JButton();
        jB_Suchen = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jL_Artikel_ID = new javax.swing.JLabel();
        jTF_Artikel_ID = new javax.swing.JTextField();
        jB_Enter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(true);
        setTitle("Artikel ändern Einstieg");
        setPreferredSize(new java.awt.Dimension(580, 300));
        setRequestFocusEnabled(false);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        jB_Zurueck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Internalframes/home.PNG"))); // NOI18N
        jB_Zurueck.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jB_Zurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ZurueckActionPerformed(evt);
            }
        });
        jToolBar1.add(jB_Zurueck);

        jB_Speichern.setText("Speichern");
        jB_Speichern.setEnabled(false);
        jToolBar1.add(jB_Speichern);

        jB_Anzeigen.setText("Anzeige/Ändern");
        jB_Anzeigen.setActionCommand("Anzeigen/Ändern");
        jB_Anzeigen.setEnabled(false);
        jToolBar1.add(jB_Anzeigen);

        jB_Loeschen.setText("Löschen");
        jB_Loeschen.setEnabled(false);
        jToolBar1.add(jB_Loeschen);

        jB_Suchen.setText("Suchen");
        jB_Suchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SuchenActionPerformed(evt);
            }
        });
        jToolBar1.add(jB_Suchen);

        jL_Artikel_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_Artikel_ID.setText("Artikelnummer:");

        jTF_Artikel_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_Artikel_IDKeyPressed(evt);
            }
        });

        jB_Enter.setText("Weiter");
        jB_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jL_Artikel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Artikel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Enter)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Artikel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_Artikel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Enter))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Methode, die aufgerufen wird, wenn man auf weiter klickt.
     *
     * @param evt automatisch generiert
     */
    /*
     * Historie:
     * 11.12.2014   Sen     angelegt
     * 14.12.2014   Sen     ueberarbeitet
     */
    private void jB_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EnterActionPerformed
        String artikelnummer = jTF_Artikel_ID.getText();
        long artikelnr;
        try {
//              Artikel mit der eingegebenen Artikelnummer wird versucht aus der Datenbank zu laden
//              Alle Felder der Sicht Artikel anlegen werden befuellt
            artikelnr = nf.parse(artikelnummer).longValue();
            Artikel artikel = GUIFactory.getDAO().getItem(artikelnr);
            artikelAnlegen.gibjTF_Artikelnummer().setText("" + artikel.getArtikelID());
            artikelAnlegen.gibjTF_Artikelname().setText(artikel.getArtikeltext());
            artikelAnlegen.gibjTA_Artikelbeschreibung().setText(artikel.getBestelltext());
            artikelAnlegen.gibjCB_Artikelkategorie().setSelectedItem(artikel.getKategorie().getKategoriename());
            artikelAnlegen.gibjTF_Einzelwert().setText("" + nf.format(artikel.getVerkaufswert()));
            artikelAnlegen.gibjTF_Bestellwert().setText("" + nf.format(artikel.getEinkaufswert()));
            artikelAnlegen.gibjCB_MwST().setSelectedItem("" + artikel.getMwST());
            artikelAnlegen.gibjTF_BestandsmengeFREI().setText("" + artikel.getFrei());
            artikelAnlegen.gibjTF_BestandsmengeRESERVIERT().setText("" + artikel.getReserviert());
            artikelAnlegen.gibjTF_BestandsmengeZULAUF().setText("" + artikel.getZulauf());
            artikelAnlegen.gibjTF_BestandsmengeVERKAUFT().setText("" + artikel.getVerkauft());
            artikelAnlegen.setVisible(true);
            this.setVisible(false);
            zuruecksetzen();
//            entsprechende Fehlermeldungen werden in der Statuszeile angezeigt
        } catch (ParseException ex) {
            this.hauptFenster.setStatusMeldung("Bitte geben Sie eine Artikelnummer ein!");
        } catch (ApplicationException ex) {
            this.hauptFenster.setStatusMeldung("Kein passender Artikel in Datenbank!");
            zuruecksetzen();
        } catch (NullPointerException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jB_EnterActionPerformed

    /**
     * Aktion die beim betätigen des Zurück-Buttons ausgeführt wird. Es wird von
     * der Guifactory die letzte aufgerufene Component abgefragt wodurch man die
     * jetzige Component verlässt und zur übergebnen Component zurück kehrt.
     *
     * @param evt automatishc generiert
     */
    /*
     * Historie:
     * 01.12.2014   Sen     angelegt
     */
    private void jB_ZurueckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ZurueckActionPerformed
        c = null;   //Initialisierung der Componentspeichervariable
        //Erhalten über GUIFactorymethode die letzte aufgerufene View und speichern diese in Variable
        c = this.factory.zurueckButton();
        this.setVisible(false);// Internalframe wird nicht mehr dargestellt
        c.setVisible(true);// Übergebene Component wird sichtbar gemacht
    }//GEN-LAST:event_jB_ZurueckActionPerformed
    /**
     * Aktion die beim betätigen schliesen des Fenster ausgefuert wird
     *
     * @param evt automatishc generiert
     */
    /*
     * Historie:
     * 01.12.2014   Sen     angelegt
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        jB_ZurueckActionPerformed(null);
    }//GEN-LAST:event_formInternalFrameClosing
    /**
     * Aktion die beim klicken auf Enter durchgefuert wird
     *
     * @param evt automatishc generiert
     */
    /*
     * Historie:
     * 02.01.2015   Sen     angelegt
     */
    private void jTF_Artikel_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_Artikel_IDKeyPressed
//        Falls enter geklickt wird, wird die Methode beim klick auf den 
//        Button Enter ausgefuehrt
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jB_EnterActionPerformed(null);
        }
    }//GEN-LAST:event_jTF_Artikel_IDKeyPressed
    /**
     * Aktion die beim klicken auf Enter durchgefuert wird
     *
     * @param evt automatishc generiert
     */
    /*
     * Historie:
     * 16.01.2015   Sen     angelegt
     */
    private void jB_SuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SuchenActionPerformed
        this.hauptFenster.rufeSuche(this);
    }//GEN-LAST:event_jB_SuchenActionPerformed
    /**
     * setterMethode für die Suche
     *
     * @param artikel Artikel Obkjekt, aus dem die artikelnummer gelesen wird
     */
    /*
     * Historie:
     * 18.01.2015   Sen     angelegt
     */
    public void setzeGP_IDAusSuche(Artikel artikel) {
        jTF_Artikel_ID.setText("" + artikel.getArtikelID());
    }
      
    /* methode, die die Eingaben zuruecksetzt
     * Historie:
     * 18.01.2015   Sen     angelegt
     */
    public void zuruecksetzen() {
        jTF_Artikel_ID.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Anzeigen;
    private javax.swing.JButton jB_Enter;
    private javax.swing.JButton jB_Loeschen;
    private javax.swing.JButton jB_Speichern;
    private javax.swing.JButton jB_Suchen;
    private javax.swing.JButton jB_Zurueck;
    private javax.swing.JLabel jL_Artikel_ID;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_Artikel_ID;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
